name: Scheduled encryption check
on:
  # schedule:
    # - cron: '0 0 * * *'
  workflow_dispatch:
jobs: 
    check-encryption:
        name: Check Encryption
        runs-on: self-hosted
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4
            
        - name: Running encryption check for all secrets
          run: bash ci/check-secrets.sh
          continue-on-error: true

    reencrypt-secrets:
        name: Reencrypt Secrets
        runs-on: self-hosted
        needs: check-encryption
        if: failure()
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          
        - name: reencrypt secrets
          run: bash ci/reencrypt-secrets.sh

        - name: Create Pull Request
          uses: peter-evans/create-pull-request@v7
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: "Reencrypt secrets"
            title: "Reencrypt secrets"
            body: |
                This PR contains reencrypted secrets that needed to be updated.
                    
                Automatically generated by the scheduled encryption check workflow.
            branch: reencrypt-secrets
            base: main
            delete-branch: true