name: Deploy Kubernetes Manifests

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Apply Kubernetes manifests
        run: bash ci/deploy.sh
